# Generated by Django 6.1 on 2026-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_featuretoggle_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("info", "Information (Blue)"),
                            ("warning", "Warning (Amber)"),
                            ("danger", "Alert / Critical (Red)"),
                            ("success", "Success (Green)"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.TextField(
                        default="We are currently performing scheduled maintenance. Please check back shortly."
                    ),
                ),
            ],
        ),
    ]
