# Generated by Django 6.1 on 2026-08-28 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("school_email", models.EmailField(blank=True, max_length=254)),
                ("major", models.CharField(blank=True, max_length=100)),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("freshman", "Freshman"),
                            ("sophomore", "Sophomore"),
                            ("junior", "Junior"),
                            ("senior", "Senior"),
                            ("graduate", "Graduate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("discord_username", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("public_profile", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
